version: 2
jobs:
  build:
      nightly:
        triggers: #use the triggers key to indicate a scheduled build
          - schedule:
            cron: "10 17 * * *" # use cron syntax to set the schedule
      docker:
        - image: circleci/python:3.6.2-stretch-browsers
      steps:
        - checkout
        - run: mkdir test-reports
        - run:
            name: Install Python Dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r ./.circleci/requirements.txt
        - save_cache:
            paths:
              - ./venv
            key: v1-dependencies-{{ checksum "./.circleci/requirements.txt" }}
        
        - run:
            name: run tests
            command: |
              . venv/bin/activate
              robot -d test-reports ./selenium/googlesearch.robot

        - store_artifacts:
            path: test-reports/
            destination: test-reports
        - store_test_results:
            path: test-reports/
