version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: win/vs2019
    steps:
      - run:
          name: Testing application
          command: robot -d ./selenium/googlesearch.robot
          no_output_timeout: 30m
          environment:
            FOO: bar