version: 2.1

machine:
  python:
    # Python version to use - Selenium requires python 3.0 and above
    version: pypy-3.6.0orbs:
dependencies:
  pre:
    - pip install selenium
    - pip install robotframework
    - pip install robotframework-selenium2library
    - pip install robotframework-requests
test:
  override:
    - robot -d ./selenium/googlesearch.robot