version: 2
jobs:
  build:
      docker:
        - image: circleci/python:3.7.4
      steps:
        - checkout
        - run:
            name: Install Python Dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r ./.circleci/requirements.txt
        - save_cache:
            paths:
              - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
        
        - run:
            name: run tests
            command: |
              . venv/bin/activate
              robot ./selenium/googlesearch.robot

        - store_artifacts:
            path: test-reports
            destination: test-reports
